name: 'biological_memory'
version: '1.0.0'
profile: 'biological_memory'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  biological_memory:
    # Working memory - always fresh view
    working_memory:
      +materialized: view
      +tags: ['continuous']
      
    # Short-term memory - incremental
    short_term:
      +materialized: incremental
      +unique_key: id
      +on_schema_change: sync_all_columns
      
    # Consolidation - incremental with cleanup
    consolidation:
      +materialized: incremental
      +unique_key: id
      +post-hook: 
        - "DELETE FROM {{ this }} WHERE consolidated_strength < 0.1"
        - "VACUUM ANALYZE {{ this }}"
      
    # Long-term memory - full table with indexes
    long_term:
      +materialized: table
      +post-hook:
        - "CREATE INDEX IF NOT EXISTS idx_retrieval ON {{ this }} (retrieval_strength DESC)"
        - "CREATE INDEX IF NOT EXISTS idx_category ON {{ this }} (semantic_category)"
        - "ANALYZE {{ this }}"

vars:
  # Biological parameters
  working_memory_capacity: 7  # Miller's magic number
  stm_duration_minutes: 30
  consolidation_threshold: 0.5
  hebbian_learning_rate: 0.1
  forgetting_rate: 0.05
  
  # Ollama configuration  
  ollama_host: "{{ env_var('OLLAMA_URL') }}"
  ollama_model: "{{ env_var('OLLAMA_MODEL') }}"
  
  # PostgreSQL source
  postgres_db_url: "{{ env_var('POSTGRES_DB_URL') }}"
  source_db: 'codex_db'