version: 2

models:
  - name: stm_hierarchical_episodes
    description: "Hierarchical episodic memory with goal-task-action decomposition"
    columns:
      - name: memory_id
        description: "Unique identifier for memory episode"
        tests:
          - unique
          - not_null
      - name: episode_type
        description: "Type of episode (goal, task, action)"
      - name: parent_memory_id
        description: "Parent episode in hierarchy"
      - name: content
        description: "Episode content"
      - name: temporal_context
        description: "When episode occurred"
      - name: spatial_context
        description: "Where episode occurred"