version: 2

models:
  - name: stable_memories
    description: "Long-term memory storage with cortical organization and semantic networks"
    columns:
      - name: memory_id
        description: "Unique identifier for stable memory"
        tests:
          - unique
          - not_null
      - name: consolidation_date
        description: "Date memory was consolidated"
      - name: cortical_column
        description: "Assigned cortical column for organization"
      - name: semantic_cluster
        description: "Semantic cluster assignment"
      - name: retrieval_strength
        description: "Current retrieval strength with decay"
      - name: association_count
        description: "Number of semantic associations"