version: 2

models:
  - name: wm_active_context
    description: "Working memory implementation with Miller's 7±2 capacity constraint and 5-minute temporal window"
    columns:
      - name: memory_id
        description: "Unique identifier for memory item"
        tests:
          - unique
          - not_null
      - name: content
        description: "Raw memory content"
      - name: timestamp
        description: "When memory was created"
      - name: strength
        description: "Memory activation strength (0.0-1.0)"
      - name: capacity_position
        description: "Position in working memory queue (1-7)"