version: 2

models:
  - name: memory_replay
    description: "Memory consolidation using Hebbian learning and hippocampal replay mechanisms"
    columns:
      - name: memory_id
        description: "Unique identifier for consolidated memory"
        tests:
          - unique
          - not_null
      - name: original_memory_id
        description: "Reference to original short-term memory"
      - name: consolidation_strength
        description: "Strength after Hebbian learning (0.0-1.0)"
      - name: consolidation_timestamp
        description: "When consolidation occurred"
      - name: replay_count
        description: "Number of hippocampal replays"
      - name: synaptic_weight
        description: "Computed synaptic weight"