name: 'biological_memory'
version: '1.0.0'
config-version: 2

# MATERIALIZATION STRATEGY:
# - Working Memory: VIEW (real-time updates, Miller's 7±2 constraint)  
# - Short-term Memory: INCREMENTAL (merge strategy, 30-minute window)
# - Consolidation: INCREMENTAL (Hebbian learning patterns)
# - Long-term Memory: TABLE (partitioned by consolidation date)
# - Semantic Networks: INCREMENTAL (connection-based updates)

# Project directories
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Database configuration
profile: 'biological_memory'

# Model configurations
models:
  biological_memory:
    # Working Memory Stage
    working_memory:
      +materialized: view
      +tags: ['biological', 'working_memory', 'continuous', 'rapid', 'performance_critical', 'real_time']
      +description: "Miller's 7±2 working memory with 5-minute window"
      +pre-hook:
        - "SET threads TO 4"
        - "SET force_hash_join TO true"

    # Short-Term Memory Stage
    short_term_memory:
      +tags: ['biological', 'short_term_memory', 'short_term', 'rapid']
      +materialized: incremental
      +unique_key: 'memory_id'
      +incremental_strategy: 'merge'
      +on_schema_change: 'sync_all_columns'

    # Short-term (alias for test compatibility)
    short_term:
      +tags: ['biological', 'short_term_memory', 'short_term', 'rapid']
      +materialized: incremental
      +unique_key: 'id'
      +incremental_strategy: 'merge'

    # Consolidation Stage
    consolidation:
      +tags: ['biological', 'consolidation', 'hourly', 'deep_sleep']
      +materialized: incremental
      +unique_key: 'memory_id'
      +incremental_strategy: 'merge'
      +indexes:
        - columns: ['memory_id']
        - columns: ['consolidation_timestamp']
      +pre-hook:
        - "SET memory_limit TO '2GB'"
      +post-hook:
        - "ANALYZE"
        - "DELETE FROM {{ this }} WHERE strength < 0.1"

    # Long-Term Memory Stage
    long_term_memory:
      +tags: ['biological', 'long_term_memory', 'long_term', 'deep_sleep', 'weekly']
      +materialized: table
      +unique_key: 'memory_id'
      +partition_by:
        field: 'consolidation_date'
        data_type: 'date'

    # Long-term (alias for test compatibility)
    long_term:
      +tags: ['biological', 'long_term_memory', 'long_term', 'deep_sleep', 'weekly']
      +materialized: table
      +unique_key: 'memory_id'
      +post-hook:
        - "CREATE INDEX IF NOT EXISTS idx_memory_consolidation ON {{ this }} (consolidation_date)"
        - "ANALYZE"

    # Semantic Networks
    semantic:
      +tags: ['biological', 'semantic', 'long_term']
      +materialized: incremental
      +unique_key: 'connection_id'
      +incremental_strategy: 'merge'

    # Analytics Views
    analytics:
      +tags: ['biological', 'analytics']
      +materialized: view

    # Insights Views
    insights:
      +tags: ['biological', 'insights']
      +materialized: view

    # Performance Monitoring
    performance:
      +tags: ['biological', 'performance']
      +materialized: ephemeral

# Variables for biological parameters
vars:
  # Miller's Magic Number
  working_memory_capacity: 7
  working_memory_capacity_base: 7
  working_memory_capacity_variance: 2
  working_memory_duration: 300  # 5 minutes in seconds
  working_memory_window_minutes: 5

  # Short-term memory duration
  short_term_memory_duration: 1800  # 30 minutes in seconds
  stm_duration_minutes: 30
  stm_decay_rate: 0.1

  # Memory thresholds
  consolidation_threshold: 0.5
  long_term_memory_threshold: 0.7
  strong_connection_threshold: 0.8
  medium_quality_threshold: 0.5
  high_quality_threshold: 0.7
  stability_threshold: 0.6
  overload_threshold: 0.9
  consolidation_interval_hours: 1

  # Hebbian learning parameters
  hebbian_learning_rate: 0.1
  synaptic_decay_rate: 0.001
  homeostasis_target: 0.5
  plasticity_threshold: 0.6
  hebbian_decay_factor: 0.95
  stdp_window_ms: 20
  ltp_threshold: 0.6
  ltd_threshold: -0.4

  # Forgetting curve parameters
  forgetting_rate: 0.05
  forgetting_time_constant: 24  # hours

  # Network parameters
  synaptic_scaling_factor: 1.5
  homeostatic_target: 0.5

  # Ollama configuration
  ollama_url: "{{ env_var('OLLAMA_URL') }}"
  ollama_host: "{{ env_var('OLLAMA_HOST', 'localhost') }}"
  ollama_model: "{{ env_var('OLLAMA_MODEL', 'llama2') }}"
  ollama_temperature: 0.7
  ollama_timeout: 30
  embedding_model: "{{ env_var('EMBEDDING_MODEL', 'nomic-embed-text') }}"

  # Database configuration
  postgres_url: "{{ env_var('POSTGRES_DB_URL', 'postgresql://localhost:5432/codex_db') }}"
  duckdb_path: "{{ env_var('DUCKDB_PATH', './biological_memory.duckdb') }}"

  # Performance settings
  max_connections: 100
  connection_timeout: 30
  query_timeout: 120

  # Biological timing parameters
  circadian_peak_hour: 14  # 2 PM
  circadian_trough_hour: 3  # 3 AM
  ultradian_cycle_minutes: 90

  # Memory thresholds
  importance_threshold: 0.3
  emotional_salience_weight: 1.2
  novelty_bonus: 0.15

# Seeds configuration
seeds:
  biological_memory:
    +quote_columns: false

# Snapshots configuration
snapshots:
  biological_memory:
    +target_schema: snapshots
    +strategy: timestamp
    +updated_at: updated_at

# On-run hooks for biological orchestration
on-run-start:
  - "{{ log('Starting biological memory pipeline', info=True) }}"
  - "SELECT 'Biological memory pipeline started at ' || CURRENT_TIMESTAMP"

on-run-end:
  - "{{ log('Biological memory pipeline complete', info=True) }}"
  - "SELECT 'Biological memory pipeline completed at ' || CURRENT_TIMESTAMP"

# Query comments for debugging
query-comment:
  comment: "{{ query_comment }}"
  append: true


# Quoting behavior
quoting:
  database: false
  schema: false
  identifier: false