biological_memory:
  outputs:
    dev:
      type: duckdb
      path: "{{ env_var('DUCKDB_PATH', '/tmp/memory.duckdb') }}"
      threads: 4

    test:
      type: duckdb
      path: "{{ env_var('TEST_DUCKDB_PATH', '/tmp/test_memory.duckdb') }}"
      threads: 2

    prod:
      type: duckdb
      path: "{{ env_var('PROD_DUCKDB_PATH', './memory.duckdb') }}"
      threads: 8

    # PostgreSQL target for write-back operations
    postgres:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST') }}"
      port: "{{ env_var('POSTGRES_PORT', '5432') | as_number }}"
      user: "{{ env_var('POSTGRES_USER') }}"
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      database: "{{ env_var('POSTGRES_DATABASE') }}"
      schema: public
      threads: 4

  target: dev
